### ISSUE TITLE
IndieGala is always Offline, and Retry doesn't work

### ISSUE THREAD

**Issue by Judassem** [burnhamup/galaxy-integration-indiegala#31]
As the title says, my IndieGala plugin has been Offline for a few months now, and the Retry button doesn't do anything. I've tried Disconnecting and Connecting my IndieGala account but it doesn't help.
![indiegala](https://github.com/user-attachments/assets/102ffca2-bc4a-477c-913d-93f19e5d2720)

[logs.zip](https://github.com/user-attachments/files/17268833/logs.zip)

**Comment by burnhamup** [comment]
The error from the logs is
```
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\GOG.com\Galaxy\plugins\installed\indiegala_a1a85742-f3e0-42ae-bde9-64ab7d0321cf\galaxy\api\jsonrpc.py", line 271, in handle
    result = await callback(*bound_args.args, **bound_args.kwargs)
  File "C:\Users\chris\AppData\Local\GOG.com\Galaxy\plugins\installed\indiegala_a1a85742-f3e0-42ae-bde9-64ab7d0321cf\galaxy\api\plugin.py", line 252, in method
    result = await handler_(*args, **kwargs)
  File "C:\Users\chris\AppData\Local\GOG.com\Galaxy\plugins\installed\indiegala_a1a85742-f3e0-42ae-bde9-64ab7d0321cf\galaxy\api\plugin.py", line 264, in wrapper
    return await self._external_task_manager.create_task(handler(*args, **kwargs), name, False)
  File "C:\Users\chris\AppData\Local\GOG.com\Galaxy\plugins\installed\indiegala_a1a85742-f3e0-42ae-bde9-64ab7d0321cf\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\chris\AppData\Local\GOG.com\Galaxy\plugins\installed\indiegala_a1a85742-f3e0-42ae-bde9-64ab7d0321cf\plugin.py", line 68, in authenticate
    return await self.get_user_info()
  File "C:\Users\chris\AppData\Local\GOG.com\Galaxy\plugins\installed\indiegala_a1a85742-f3e0-42ae-bde9-64ab7d0321cf\plugin.py", line 100, in get_user_info
    return Authentication(data['_indiegala_user_id'], data['_indiegala_username'])
KeyError: '_indiegala_user_id'
```

I think this means that the way I connect has changed. I don't really want to go back to trying to scrape the games from the website, because you get logged out every few days which was just miserable for a plugin. 

The current method I reverse engineered from the Indie Gala desktop launcher, but I can't login with that at all now - I'm wondering if whatever Indie Gala changed broke their desktop client as well. I'll keep an eye on it, but I don't have a clear path to fixing this right now,

**Comment by Ascendens** [comment]
+1

**Comment by mortenanakin** [comment]
+1 here too

**Comment by burnhamup** [comment]
I'm monitoring https://forums.indiegala.com/threads/indiegala-desktop-client-will-not-log-in-reports-error.25149/ but it seems no one can login to the standalone client. If it looks like that isn't getting fixed anytime soon, I guess the next idea is to go back to scraping the website directly. The issue there is that the plugin gets disconnected every few days.

**Comment by beer-matt** [comment]
My standalone client started working again, so retested the IG plugin which also seems to be working again (had to disconnect/reconnect but seems ok again now).. 👍

**Comment by Judassem** [comment]
Same here. The same problem was also in Playnite and it's resolved too.
